- name : Metatron Discovery
  image : metatron.png
  description : Metatron Discovery is a big data analysis platform supports overall process from data cleansing to visualization. Where more than 10 billion of large volume data are processed in seconds, analyze data on variety of levels, discover insights and apply it on your business right away.
  github-url : https://github.com/metatron-app/metatron-discovery
  homepage-url : https://metatron.app/

- name : TACO
  image : taco.jpg
  description : TACO (SKT All Container OpenStack) is designed to provide convenient and stable use for enterprises by comprehensively implementing virtualization of servers, networks, and storage required for cloud infrastructure.
  github-url : https://github.com/openinfradev/tacoplay
  homepage-url : https://openinfradev.github.io/

- name : SONA
  image : sona.png
  description : SONA(Simplified Overlay Network Architecture) is an optimized tenant network virtualization service for Cloud-based data center. Basically, it is a set of ONOS applications which provides OpenStack Neutron ML2 mechanism driver and L3 service plugin.
  github-url : https://github.com/sonaproject
  homepage-url :

- name : KoBERT
  image : kobert.png
  description : KoBERT(Korean BERT pre-trained cased) is a language AI model that understands Korean and was developed to overcome the Korean limitation of BERT(Bidirectional Encoder Representations from Transformers) developed by Google.
  github-url : https://github.com/SKTBrain/KoBERT
  homepage-url : 

- name : KoGPT2
  image : koGPT2.jpg
  description : KoGPT-2 is an open source GPT-2 (Generative Pretrained Transformer-2) model pre-trained with Korean text to improve Korean machine learning (ML) performance. KoGPT-2 can be used for chatbots, search engines and other purposes.
  github-url : https://github.com/SKT-AI/KoGPT2
  homepage-url : 

- name : H8L(Hwangsaeul)
  image : h8l.jpg
  description : H8L(Hwangsaeul) is a project to build SRT ecosystem. We are planning to build new streaming system for a cloud-based video surveillance service. In the new system, Secure Reliable Transport (SRT) will be used as a base protocol to archive the critical requirements; ultra-low latency, packet loss recovery.
  github-url : https://github.com/hwangsaeul
  homepage-url : https://hwangsaeul.github.io/